# macOS应用规则集
PROCESS-NAME,Codex
PROCESS-NAME,Codex Helper
PROCESS-NAME,ChatGPT
PROCESS-NAME,ChatGPT Helper
PROCESS-NAME,Codex (Service)
PROCESS-NAME,Codex Computer Use
PROCESS-NAME,Gemini
PROCESS-NAME,Gemini Helper
PROCESS-NAME,Claude
PROCESS-NAME,Claude Helper
PROCESS-NAME,Copilot
PROCESS-NAME,Copilot Helper
PROCESS-NAME,Cursor
PROCESS-NAME,Cursor Helper
PROCESS-NAME,Antigravity IDE
PROCESS-NAME,Antigravity IDE Helper
PROCESS-NAME,Antigravity IDE Helper (Plugin)
PROCESS-NAME,Antigravity
PROCESS-NAME,Antigravity Helper
PROCESS-NAME,Antigravity Helper (Plugin)
PROCESS-NAME,language_server_macos_arm
PROCESS-PATH,/Applications/ChatGPT.app/Contents/Resources/codex
PROCESS-PATH,/Applications/Antigravity IDE.app/Contents/MacOS/Electron
PROCESS-PATH,/Applications/Antigravity.app/Contents/MacOS/Electron
